<a href="https://colab.research.google.com/github/talha-q/Pytorch_learning/blob/main/30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
T=torch.rand(1,16)
T

tensor([[0.2805, 0.5631, 0.9163, 0.9567, 0.9215, 0.5761, 0.6309, 0.5016, 0.0708,
         0.4116, 0.6666, 0.3653, 0.9359, 0.1238, 0.1941, 0.0194]])

In [3]:
T.reshape(8,2)

tensor([[0.2805, 0.5631],
        [0.9163, 0.9567],
        [0.9215, 0.5761],
        [0.6309, 0.5016],
        [0.0708, 0.4116],
        [0.6666, 0.3653],
        [0.9359, 0.1238],
        [0.1941, 0.0194]])

In [5]:
T.reshape(2,8)

tensor([[0.2805, 0.5631, 0.9163, 0.9567, 0.9215, 0.5761, 0.6309, 0.5016],
        [0.0708, 0.4116, 0.6666, 0.3653, 0.9359, 0.1238, 0.1941, 0.0194]])

In [6]:
T.reshape(4,4)

tensor([[0.2805, 0.5631, 0.9163, 0.9567],
        [0.9215, 0.5761, 0.6309, 0.5016],
        [0.0708, 0.4116, 0.6666, 0.3653],
        [0.9359, 0.1238, 0.1941, 0.0194]])

In [7]:
T.view(4,4)

tensor([[0.2805, 0.5631, 0.9163, 0.9567],
        [0.9215, 0.5761, 0.6309, 0.5016],
        [0.0708, 0.4116, 0.6666, 0.3653],
        [0.9359, 0.1238, 0.1941, 0.0194]])

In [8]:
torch.stack(T,T,T)

TypeError: ignored

In [13]:
A=torch.rand(3)
A

tensor([0.4741, 0.9627, 0.9547])

In [16]:
torch.stack([A,A,A,A],dim=0)

tensor([[0.4741, 0.9627, 0.9547],
        [0.4741, 0.9627, 0.9547],
        [0.4741, 0.9627, 0.9547],
        [0.4741, 0.9627, 0.9547]])

In [18]:
T=torch.tensor([255,255,3])
T

tensor([255, 255,   3])

In [20]:
T.permute([3,255,255])

RuntimeError: ignored

In [21]:
import torch
C=torch.rand(255,255,3)

In [22]:
C

tensor([[[0.6140, 0.1889, 0.0104],
         [0.3833, 0.2444, 0.2212],
         [0.8473, 0.1231, 0.3943],
         ...,
         [0.5548, 0.5679, 0.3918],
         [0.3561, 0.9868, 0.7114],
         [0.0440, 0.6898, 0.3621]],

        [[0.9932, 0.9829, 0.5226],
         [0.2136, 0.2843, 0.7217],
         [0.4682, 0.1393, 0.9668],
         ...,
         [0.6480, 0.7288, 0.5129],
         [0.0774, 0.9800, 0.4974],
         [0.9102, 0.7019, 0.6697]],

        [[0.6623, 0.3555, 0.7469],
         [0.0407, 0.4332, 0.1575],
         [0.8458, 0.3393, 0.4446],
         ...,
         [0.6072, 0.5870, 0.5515],
         [0.3914, 0.6449, 0.1943],
         [0.7606, 0.1507, 0.8713]],

        ...,

        [[0.1565, 0.1400, 0.4379],
         [0.8972, 0.8927, 0.0970],
         [0.8669, 0.3810, 0.0643],
         ...,
         [0.3440, 0.2398, 0.7118],
         [0.9678, 0.7541, 0.7785],
         [0.0105, 0.9513, 0.8418]],

        [[0.1728, 0.3276, 0.2478],
         [0.4675, 0.0873, 0.3404],
         [0.

In [24]:
C.shape

torch.Size([255, 255, 3])

In [25]:
C.ndim

3

In [28]:
C.permute(2,1,0),C.shape

(tensor([[[0.6140, 0.9932, 0.6623,  ..., 0.1565, 0.1728, 0.4313],
          [0.3833, 0.2136, 0.0407,  ..., 0.8972, 0.4675, 0.0474],
          [0.8473, 0.4682, 0.8458,  ..., 0.8669, 0.6955, 0.6867],
          ...,
          [0.5548, 0.6480, 0.6072,  ..., 0.3440, 0.0177, 0.7495],
          [0.3561, 0.0774, 0.3914,  ..., 0.9678, 0.2509, 0.0239],
          [0.0440, 0.9102, 0.7606,  ..., 0.0105, 0.5101, 0.0369]],
 
         [[0.1889, 0.9829, 0.3555,  ..., 0.1400, 0.3276, 0.6810],
          [0.2444, 0.2843, 0.4332,  ..., 0.8927, 0.0873, 0.9294],
          [0.1231, 0.1393, 0.3393,  ..., 0.3810, 0.0650, 0.6081],
          ...,
          [0.5679, 0.7288, 0.5870,  ..., 0.2398, 0.3582, 0.2690],
          [0.9868, 0.9800, 0.6449,  ..., 0.7541, 0.4069, 0.7947],
          [0.6898, 0.7019, 0.1507,  ..., 0.9513, 0.2995, 0.3819]],
 
         [[0.0104, 0.5226, 0.7469,  ..., 0.4379, 0.2478, 0.1674],
          [0.2212, 0.7217, 0.1575,  ..., 0.0970, 0.3404, 0.6660],
          [0.3943, 0.9668, 0.4446,  ...,

In [29]:
C.shape

torch.Size([255, 255, 3])

In [30]:
C.permute(0,2,1).shape

torch.Size([255, 3, 255])

In [31]:
C.permute(1,0,2).shape

torch.Size([255, 255, 3])

In [36]:
A=torch.arange(1,10)
A,A.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [48]:
B=A.reshape(1,3,3)


In [49]:
B[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [50]:
B.shape

torch.Size([1, 3, 3])

In [51]:
B[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [52]:
B[0,0]

tensor([1, 2, 3])

In [54]:
B[0,0,2]

tensor(3)

In [59]:
#here we can also use : to select all elements of a dimension, for that purpose we can do something like below
#: it means it selects all elements of the dimensions to give us a value.
B[:,:,0], B[0,1,:]

(tensor([[1, 4, 7]]), tensor([4, 5, 6]))

In [60]:
#to get number 9 we can do this
B[0][2][2]

tensor(9)

In [61]:
B[:,2,2]

tensor([9])

In [62]:
B[:,:,2]

tensor([[3, 6, 9]])

In [65]:
import numpy as np
N=np.arange(0,9)
N

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
NT=torch.from_numpy(N)
NT

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])